// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/workout/data/exercise_entry_entity.dart';
import 'features/workout/data/workout_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1588204839646210899),
      name: 'WorkoutEntity',
      lastPropertyId: const obx_int.IdUid(4, 1868634259132625409),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 573266632809431305),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8622288868798748272),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8197658574074060156),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1868634259132625409),
            name: 'completed',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 5803202301660653731),
            name: 'exercises',
            targetId: const obx_int.IdUid(2, 716498657038353113))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 716498657038353113),
      name: 'ExerciseEntryEntity',
      lastPropertyId: const obx_int.IdUid(12, 7831683687323495686),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2919497849192101967),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6538600488811026243),
            name: 'sets',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5120717072514805658),
            name: 'reps',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5718079136015928835),
            name: 'workoutId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5758959352857040000),
            name: 'weight',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7831683687323495686),
            name: 'exerciseName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 716498657038353113),
      lastIndexId: const obx_int.IdUid(4, 1927285796835195713),
      lastRelationId: const obx_int.IdUid(1, 5803202301660653731),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [
        5918567257528382604,
        8381125699145556622,
        1489908074919184526,
        1927285796835195713
      ],
      retiredPropertyUids: const [
        1452522710367003196,
        5467121881384590789,
        394194076137105696,
        7056583764010970254,
        605570369294457941,
        3496391087645469579
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    WorkoutEntity: obx_int.EntityDefinition<WorkoutEntity>(
        model: _entities[0],
        toOneRelations: (WorkoutEntity object) => [],
        toManyRelations: (WorkoutEntity object) => {
              obx_int.RelInfo<WorkoutEntity>.toMany(1, object.id):
                  object.exercises
            },
        getId: (WorkoutEntity object) => object.id,
        setId: (WorkoutEntity object, int id) {
          object.id = id;
        },
        objectToFB: (WorkoutEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.date.millisecondsSinceEpoch);
          fbb.addBool(3, object.completed);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final completedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object = WorkoutEntity(
              name: nameParam, date: dateParam, completed: completedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<WorkoutEntity>(
              object.exercises,
              store,
              obx_int.RelInfo<WorkoutEntity>.toMany(1, object.id));
          return object;
        }),
    ExerciseEntryEntity: obx_int.EntityDefinition<ExerciseEntryEntity>(
        model: _entities[1],
        toOneRelations: (ExerciseEntryEntity object) => [],
        toManyRelations: (ExerciseEntryEntity object) => {},
        getId: (ExerciseEntryEntity object) => object.id,
        setId: (ExerciseEntryEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ExerciseEntryEntity object, fb.Builder fbb) {
          final exerciseNameOffset = fbb.writeString(object.exerciseName);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.sets);
          fbb.addInt64(3, object.reps);
          fbb.addInt64(8, object.workoutId);
          fbb.addFloat64(10, object.weight);
          fbb.addOffset(11, exerciseNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final workoutIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final exerciseNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final setsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final repsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final weightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final object = ExerciseEntryEntity(
              workoutId: workoutIdParam,
              exerciseName: exerciseNameParam,
              sets: setsParam,
              reps: repsParam,
              weight: weightParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [WorkoutEntity] entity fields to define ObjectBox queries.
class WorkoutEntity_ {
  /// see [WorkoutEntity.id]
  static final id =
      obx.QueryIntegerProperty<WorkoutEntity>(_entities[0].properties[0]);

  /// see [WorkoutEntity.name]
  static final name =
      obx.QueryStringProperty<WorkoutEntity>(_entities[0].properties[1]);

  /// see [WorkoutEntity.date]
  static final date =
      obx.QueryDateProperty<WorkoutEntity>(_entities[0].properties[2]);

  /// see [WorkoutEntity.completed]
  static final completed =
      obx.QueryBooleanProperty<WorkoutEntity>(_entities[0].properties[3]);

  /// see [WorkoutEntity.exercises]
  static final exercises =
      obx.QueryRelationToMany<WorkoutEntity, ExerciseEntryEntity>(
          _entities[0].relations[0]);
}

/// [ExerciseEntryEntity] entity fields to define ObjectBox queries.
class ExerciseEntryEntity_ {
  /// see [ExerciseEntryEntity.id]
  static final id =
      obx.QueryIntegerProperty<ExerciseEntryEntity>(_entities[1].properties[0]);

  /// see [ExerciseEntryEntity.sets]
  static final sets =
      obx.QueryIntegerProperty<ExerciseEntryEntity>(_entities[1].properties[1]);

  /// see [ExerciseEntryEntity.reps]
  static final reps =
      obx.QueryIntegerProperty<ExerciseEntryEntity>(_entities[1].properties[2]);

  /// see [ExerciseEntryEntity.workoutId]
  static final workoutId =
      obx.QueryIntegerProperty<ExerciseEntryEntity>(_entities[1].properties[3]);

  /// see [ExerciseEntryEntity.weight]
  static final weight =
      obx.QueryDoubleProperty<ExerciseEntryEntity>(_entities[1].properties[4]);

  /// see [ExerciseEntryEntity.exerciseName]
  static final exerciseName =
      obx.QueryStringProperty<ExerciseEntryEntity>(_entities[1].properties[5]);
}
